### ISSUE TITLE
Despliegue en netlify

### ISSUE THREAD

**Issue by DanMAMO** [ULL-ESIT-DMSI-2324/intro2sd-daniel-marichal-monsonis-alu0101014548#1]

**Comment by DanMAMO** [comment]
La página de Netlify me solicita una subscripción para su uso, pero supongo que esta no es la intención de la asignatura. @crguezl ,¿hay alguna forma de evitar la barrera de pago que se me esté escapando?

Un cordial saludo,
Daniel

**Comment by crguezl** [comment]
Si, el asunto se arregla haciendo publico el repo
